# This rule is not used by the project pihole-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pihole-operator.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: blocklist-viewer-role
rules:
- apiGroups:
  - pihole-operator.org
  resources:
  - blocklists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pihole-operator.org
  resources:
  - blocklists/status
  verbs:
  - get
