# This rule is not used by the project pihole-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pihole-operator.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: blocklist-admin-role
rules:
- apiGroups:
  - pihole-operator.org
  resources:
  - blocklists
  verbs:
  - '*'
- apiGroups:
  - pihole-operator.org
  resources:
  - blocklists/status
  verbs:
  - get
