# This rule is not used by the project pihole-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the pihole-operator.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: pihole-editor-role
rules:
- apiGroups:
  - pihole-operator.org
  resources:
  - piholes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pihole-operator.org
  resources:
  - piholes/status
  verbs:
  - get
